# Standards: 0.1
---
- name: Kill slack
  command: killall Slack
  register: slack_kill
  failed_when: slack_kill.rc != 0 and "No matching processes belonging to you were found" not in slack_kill.stderr
  become: "{{ (slack_user != ansible_user_id) | bool }}"
  become_user: "{{ slack_user }}"

- name: Start slack
  when: slack_started
  command: open -j /Applications/Slack.app
  become: "{{ (slack_user != ansible_user_id) | bool }}"
  become_user: "{{ slack_user }}"

...
